[[param]]
name = "network"
type = "String"
default = "\"bitcoin\".into()"
doc = "Which Bitcoin network to use."

[[param]]
name = "datadir"
type = "String"
default = "\"~/.kernel-node\".into()"
doc = "Data directory for blockchain and configuration."

[[param]]
name = "connect"
type = "String"
optional = true
merge_fn = "crate::join_connect"
doc = "Connect only to the specified node (format: ip:port). May be given more than once."

[[param]]
name = "daemon"
type = "bool"
default = "false"
doc = "Run the server as a daemon"

[[param]]
name = "sp_keys_file"
type = "String"
optional = true
doc = "Path to a binary silent payments keys file to import at startup."
